# Server configuration
server:
  port: 9998
  tomcat:
    max-threads: 1000
    max-connections: 1000
    accept-count: 1000
#mybatis
mybatis:
  #Mapper.xml所在的位置
  mapper-locations: classpath:mapping/**/*.xml
  #entity扫描的包名
  type-aliases-package: style.jason.mybatisdemo.domain.modul
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启 user_name转化成userName与实体类属性
    map-underscore-to-camel-case: true
spring:
  profiles:
    active: dev
  application:
    name: mybatis-demo
  datasource:
    druid:
      #最大活跃数
      max-active: 80
      #初始化数量
      initial-size: 60
      min-idle: 60
      #最大连接等待超时时间
      max-wait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat,wall
      connectionInitSqls: "set names utf8mb4"
logging:
  level:
    style:
      jason:
        debug
debug: true
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springBootDemo?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456